Some minor fixes to earlier python checks.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -39,7 +39,7 @@ parse_args $*
 #
 # Compiler
 #
-check_cc || die
+check_cc || die 'No C compiler found'
 check_cc_header execinfo
 check_cc_option mmx
 check_cc_option sse2
@@ -47,9 +47,10 @@ check_cc_option sse2
 #
 # Python
 #
-check_py || die
-check_py_import zlib pyzlib || die
-check_py_import tarfile pytar || die
+check_py || die 'No PYTHON binary found'
+check_py_import zlib pyzlib || die "Python module missing: zlib"
+check_py_import tarfile pytar || die "Python module missing: tarfile"
+# Note: the above could/should be made optional
 
 #
 # SSL
@@ -99,7 +100,7 @@ fi
 if enabled linuxdvb && enabled dvbscan; then
   if [ ! -d ${ROOTDIR}/data/dvb-scan ]; then
     echo -n "Fetching dvb-scan files... "
-    ${ROOTDIR}/support/getmuxlist &> /dev/null || die "Failed to fetch dvb-scan files (use --disable-dvbscan to skip)"
+    ${PYTHON} ${ROOTDIR}/support/getmuxlist &> /dev/null || die "Failed to fetch dvb-scan files (use --disable-dvbscan to skip)"
     echo "done"
   fi
 fi
