[configure]: fix for omx_rpi

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -550,8 +550,16 @@ if enabled ffmpeg_static; then
 
   # omx
   if enabled omx; then
-    check_cc_header OMX_Core || die "OpenMAX IL not found"
-    check_cc_header "/opt/vc/include/bcm_host.h" omx_rpi
+    has_omx=true
+    check_cc_header "/opt/vc/include/bcm_host" omx_rpi
+    if enabled omx_rpi; then
+      check_cc_header "/opt/vc/include/IL/OMX_Core" omx || has_omx=false
+    else
+      check_cc_header OMX_Core omx || has_omx=false
+    fi
+    if ! $has_omx; then
+      die "OpenMAX IL not found"
+    fi
   fi
 
 else
