build: remove use of submodule for dvb-scan data
Revert back to manually fetching, though now its a git report its somewhat
simpler and we'll avoid using a separate script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -174,10 +174,17 @@ fi
 # DVB scan
 #
 if enabled linuxdvb && enabled dvbscan; then
-  [ ! -d ${ROOTDIR}/data/dvb-scan/.git ] && rm -rf $ROOTDIR/data/dvb-scan/*
   printf "${TAB}" "fetching dvb-scan files ..."
-  git submodule update --init &> /dev/null\
-    || die "failed (use --disable-dvbscan)"
+  if [ -d ${ROOTDIR}/data/dvb-scan/.git ]; then
+    (cd ${ROOTDIR}/data/dvb-scan; git pull) &> /dev/null
+  else
+    URL=git://linuxtv.org/dtv-scan-tables.git
+    git clone $URL ${ROOTDIR}/data/dvb-scan &> /dev/null
+    if [ $? -ne 0 ]; then
+      echo "fail"
+      die "Failed to fetch dvb-scan data (use --disable-dvbscan)"
+    fi
+  fi
   echo "ok"
 fi
 
